[workspace]
resolver = "2"
members = ["blockchain", "node", "network"]

[workspace.dependencies]
serde = { version = "1.0.198", features = ["derive"]}
chrono = "0.4.38"
serde_json = "1.0.116"
libp2p = "0.53.2"
tokio = "1.37.0"