
[package]
name = "network"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
libp2p = { workspace = true, features = ["tokio", "gossipsub", "mdns", "noise", "macros", "tcp", "yamux", "quic"]}
once_cell = "1.19.0"
tokio = { workspace = true, features = ["full"]}
