[package]
name = "blockchain"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10.8"
serde = { workspace = true }
chrono = { workspace = true }
serde_json = { workspace = true }
uuid = { version = "1.8.0", features = ["v4"] }
